name: py38
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip>=18.0
  - conda>=4.5.9
  - patchelf=0.9
  - pytorch
  - torchaudio
  - cudatoolkit=11.3 -c
  - pip:
      - devpack
      - -r requirements.txt
